site_name: Apache Hop Knowledge Base
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - content.code.annotate
repo_url: https://github.com/your-org/hop-docs
repo_name: hop-docs
nav:
  - Home: index.md
  - Apache Hop:
      - Einführung: was_ist_apache_hop.md
      - Guidelines: hop_developer_guidelines.md
      - Datenproduktbeschreibung: datenproduktbeschreibung_technisch.md